# Explorando GeoRef-AR API

## Extraction y preprocessing 

In [3]:
import pandas as pd
from IPython.display import display

In [4]:
df = pd.read_csv('provincias_cp_localidades.csv', encoding='latin-1')

In [5]:
df.head()

nacionalidad provincia_part cp_part      loc_part
0           AR            NaN    1704           NaN
1           AR            NaN    1704           NaN
2   30/06/2015            NaN      CF          1006
3           AR            NaN    1688  12 DE AGOSTO
4   05/08/1987            NaN      BA          1684

Hay algunos problemas con los datos. Pasare a limpiar aquellos campos que no sean "string" en `nacionalidad`, ni "integer" en `cp_part`

In [6]:
df.nacionalidad.str.contains('/').sum()

2

In [7]:
df.nacionalidad.isna().sum()

10

Son solo dos con fecha y 10 valores nulos. Paso a removerlos directamente

In [8]:
#df['cp_part'] = df['cp_part'].apply(lambda x: pd.to_numeric(x, errors='coerce', downcast = 'integer')).copy()

In [9]:
df2 = df.loc[df.nacionalidad.str.contains('/') == False].reset_index(drop = True) #elimina los Nan y los campos con fecha
df2.head()

nacionalidad provincia_part cp_part      loc_part
0           AR            NaN    1704           NaN
1           AR            NaN    1704           NaN
2           AR            NaN    1688  12 DE AGOSTO
3           AR            NaN    6660    25 DE MAYO
4           AR            NaN       0    9 DE ABRIL

In [10]:
df2.nacionalidad.isna().sum()

0

---

## Probando el modulo get_centroides (el nombre puede cambiar)
Toma datos de la API de https://datosgobar.github.io/georef-ar-api/

In [11]:
import get_centroides as geo

In [12]:
geo.get_centroides('localidades','Olivos')

[{'categoria': 'Localidad simple',
  'centroide': {'lat': -33.4394729739475, 'lon': -64.8316610855999},
  'departamento': {'id': '14098', 'nombre': 'Río Cuarto'},
  'id': '14098270000',
  'localidad_censal': {'id': '14098270', 'nombre': 'Suco'},
  'municipio': {'id': '142588', 'nombre': 'Suco'},
  'nombre': 'SUCO',
  'provincia': {'id': '14', 'nombre': 'Córdoba'}},
 {'categoria': 'Entidad',
  'centroide': {'lat': -28.407625810512, 'lon': -67.0961546311905},
  'departamento': {'id': '46119', 'nombre': 'San Blas de Los Sauces'},
  'id': '46119010008',
  'localidad_censal': {'id': '46119010', 'nombre': 'Salicas - San Blas'},
  'municipio': {'id': '460119', 'nombre': 'San Blas de los Sauces'},
  'nombre': 'SALICAS',
  'provincia': {'id': '46', 'nombre': 'La Rioja'}},
 {'categoria': 'Componente de localidad compuesta',
  'centroide': {'lat': -34.6132917290185, 'lon': -58.3887517365082},
  'departamento': {'id': None, 'nombre': None},
  'id': '02000010000',
  'localidad_censal': {'id': '0200

In [13]:
geo.get_centroides('localidades','olivos', provincia = 'buenos aires')

[{'categoria': 'Localidad simple',
  'centroide': {'lat': -37.1774801030509, 'lon': -62.7578962604015},
  'departamento': {'id': '06007', 'nombre': 'Adolfo Alsina'},
  'id': '06007010000',
  'localidad_censal': {'id': '06007010', 'nombre': 'Carhué'},
  'municipio': {'id': '060007', 'nombre': 'Adolfo Alsina'},
  'nombre': 'CARHUE',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {'categoria': 'Localidad simple',
  'centroide': {'lat': -37.4486186469627, 'lon': -63.117609405389},
  'departamento': {'id': '06007', 'nombre': 'Adolfo Alsina'},
  'id': '06007020000',
  'localidad_censal': {'id': '06007020',
   'nombre': 'Colonia San Miguel Arcángel'},
  'municipio': {'id': '060007', 'nombre': 'Adolfo Alsina'},
  'nombre': 'COLONIA SAN MIGUEL ARCANGEL',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {'categoria': 'Localidad simple',
  'centroide': {'lat': -37.3173292631958, 'lon': -63.2331690622102},
  'departamento': {'id': '06007', 'nombre': 'Adolfo Alsina'},
  'id': '060

In [14]:
geo.get_localidad('Buenos Aires','Olivos')

[{'categoria': 'Localidad simple',
  'centroide': {'lat': -37.1774801030509, 'lon': -62.7578962604015},
  'departamento': {'id': '06007', 'nombre': 'Adolfo Alsina'},
  'id': '06007010000',
  'localidad_censal': {'id': '06007010', 'nombre': 'Carhué'},
  'municipio': {'id': '060007', 'nombre': 'Adolfo Alsina'},
  'nombre': 'CARHUE',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {'categoria': 'Localidad simple',
  'centroide': {'lat': -37.4486186469627, 'lon': -63.117609405389},
  'departamento': {'id': '06007', 'nombre': 'Adolfo Alsina'},
  'id': '06007020000',
  'localidad_censal': {'id': '06007020',
   'nombre': 'Colonia San Miguel Arcángel'},
  'municipio': {'id': '060007', 'nombre': 'Adolfo Alsina'},
  'nombre': 'COLONIA SAN MIGUEL ARCANGEL',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {'categoria': 'Localidad simple',
  'centroide': {'lat': -37.3173292631958, 'lon': -63.2331690622102},
  'departamento': {'id': '06007', 'nombre': 'Adolfo Alsina'},
  'id': '060

---

## Aplicando get_centroides al DF

In [15]:
df2.provincia_part.unique()

array([nan, 'BA', 'CA', 'CB', 'CF', 'CH', 'CO', 'CT', 'ER', 'FO', 'JU',
       'LP', 'MI', 'MZ', 'NE', 'RN', 'SA', 'SC', 'SE', 'SF', 'SJ', 'SL',
       'TF', 'TU'], dtype=object)

In [16]:
df2.head()

nacionalidad provincia_part cp_part      loc_part
0           AR            NaN    1704           NaN
1           AR            NaN    1704           NaN
2           AR            NaN    1688  12 DE AGOSTO
3           AR            NaN    6660    25 DE MAYO
4           AR            NaN       0    9 DE ABRIL

In [17]:
print(df2.loc_part[3])
geo.get_centroides('localidades', df2.loc_part[3])

25 DE MAYO


[{'categoria': 'Localidad simple',
  'centroide': {'lat': -33.4394729739475, 'lon': -64.8316610855999},
  'departamento': {'id': '14098', 'nombre': 'Río Cuarto'},
  'id': '14098270000',
  'localidad_censal': {'id': '14098270', 'nombre': 'Suco'},
  'municipio': {'id': '142588', 'nombre': 'Suco'},
  'nombre': 'SUCO',
  'provincia': {'id': '14', 'nombre': 'Córdoba'}},
 {'categoria': 'Entidad',
  'centroide': {'lat': -28.407625810512, 'lon': -67.0961546311905},
  'departamento': {'id': '46119', 'nombre': 'San Blas de Los Sauces'},
  'id': '46119010008',
  'localidad_censal': {'id': '46119010', 'nombre': 'Salicas - San Blas'},
  'municipio': {'id': '460119', 'nombre': 'San Blas de los Sauces'},
  'nombre': 'SALICAS',
  'provincia': {'id': '46', 'nombre': 'La Rioja'}},
 {'categoria': 'Componente de localidad compuesta',
  'centroide': {'lat': -34.6132917290185, 'lon': -58.3887517365082},
  'departamento': {'id': None, 'nombre': None},
  'id': '02000010000',
  'localidad_censal': {'id': '0200

In [18]:
df2.tail()

nacionalidad provincia_part cp_part             loc_part
1410           AR             TU    4000  SAN MIGUEL DE TUCUM
1411           AR             TU    4000  SAN MIGUEL DE TUCUM
1412           AR             TU    4107              TUCUMAN
1413           AR             TU    4107          YERBA BUENA
1414           AR             TU    4107          YERBA BUENA

In [18]:
geo.get_centroides('localidades', df2.loc_part[1414], provincia = df2.provincia_part[1414], aplanar = True)

[{'categoria': 'Localidad simple',
  'centroide_lat': -26.6843396000243,
  'centroide_lon': -65.0481349066456,
  'departamento_id': '90007',
  'departamento_nombre': 'Burruyacú',
  'id': '90007010000',
  'localidad_censal_id': '90007010',
  'localidad_censal_nombre': 'Barrio San Jorge',
  'municipio_id': '908021',
  'municipio_nombre': 'El Naranjo y el Sunchal',
  'nombre': 'BARRIO SAN JORGE',
  'provincia_id': '90',
  'provincia_nombre': 'Tucumán'},
 {'categoria': 'Localidad simple',
  'centroide_lat': -26.7583605607957,
  'centroide_lon': -65.0693888917573,
  'departamento_id': '90007',
  'departamento_nombre': 'Burruyacú',
  'id': '90007020000',
  'localidad_censal_id': '90007020',
  'localidad_censal_nombre': 'El Chañar',
  'municipio_id': '908014',
  'municipio_nombre': 'El Chañar',
  'nombre': 'EL CHAÑAR',
  'provincia_id': '90',
  'provincia_nombre': 'Tucumán'},
 {'categoria': 'Localidad simple',
  'centroide_lat': -26.6571859218044,
  'centroide_lon': -65.0483602838482,
  'depa

## Breve analisis descriptivo para saber la cantidad de localidades

### Cómo está compuesto el CPA
El CPA amplía la información del código postal, incorporando 4 letras que permiten identificar cada cara de manzana en las localidades de más de 500 habitantes. Las localidades de menos de 500 habitantes poseen un único CPA.
La unica forma de que el CP nos sea util es si contamos con datos de la provincia.

https://xn--cdigos-postales-vrb.cybo.com/argentina/ es una pagina bastante completa con listado de CP. Sin embargo debe haber una API sencilla para consultar estos datos.<br>
Otra es http://mapanet.eu/Postal_Codes/?C=AR&n=0&r0=&r1=&r2=&r3=&r4=&l=0

Dado que todos los datos son solo 4 digitos se esta usando el codigo postal viejo. El isguiente listado nos da una idea aproximada de que region seria basados en el CP
https://en.wikipedia.org/wiki/Postal_codes_in_Argentina

In [19]:
df2.loc_part.unique().size #Numero de localidades unicas

654

In [20]:
df2.loc_part.isna().sum() #Solo 4 son NA. Podriamos verlo mas detalladamente

4

In [21]:
df2.groupby(by=['loc_part','provincia_part']).count().sort_values('cp_part', ascending = False)

nacionalidad  cp_part
loc_part          provincia_part                       
LOMAS DEL MIRADOR CF                         2        2
LAS FLORES        BA                         2        2
LANUS OESTE       BA                         2        2
SANTOS LUGARES    BA                         2        2
LANUS ESTE        BA                         2        2
...                                        ...      ...
                  CF                         1        1
LANUES OESTE      BA                         1        1
LANOS OESTE       BA                         1        1
LANGUEYU          BA                         1        1
san isidro        BA                         1        1

[699 rows x 2 columns]

Cuando vemos la cantidad de rows podemos notar que hay casos en los que 'loc_part' no es suficiente para agregar a todos los datos

In [60]:
df2.groupby(by=['loc_part','provincia_part','cp_part'],).count().sort_values('nacionalidad', ascending = False)

nacionalidad
loc_part            provincia_part cp_part              
SAN MARTIN          BA             1650                2
GLEW                BA             1856                2
SAN ANTONIO OESTE   RN             8520                2
GREGORIO DE LA FERR BA             1752                2
GREGORIA LAFERRERE  BA             1757                2
...                                                  ...
Gualeguaychú        ER             2820                1
HAEDO               CF             1708                1
HAEDO SUR           BA             1706                1
HOYO DE EPUYÉN      BA             1708                1
san isidro          BA             1642                1

[789 rows x 1 columns]

In [61]:
df2.loc[df2.loc_part.isna()] 

nacionalidad provincia_part cp_part loc_part
0              AR            NaN    1704      NaN
1              AR            NaN    1704      NaN
1130           AR             CF    1884      NaN
1131           AR             CF    1884      NaN

Solo cuatro casos no presentan `loc_part`, inforamcion minima que precisamos. Los primeros dos indices son practicamente inutiles. Veamos si podemos ver cuales son los loc_part de `CF`

In [62]:
df2.loc[df2.provincia_part == 'CF']

nacionalidad provincia_part cp_part         loc_part
1130           AR             CF    1884              NaN
1131           AR             CF    1884              NaN
1132           AR             CF    1425               -1
1133           AR             CF    1870       AVELLANEDA
1134           AR             CF    1870       AVELLANEDA
...           ...            ...     ...              ...
1244           AR             CF    1603   VILLA MARTELLI
1245           AR             CF    1709  VILLA SARMIENTO
1246           AR             CF    1709  VILLA SARMIENTO
1247           AR             CF    1875            WILDE
1248           AR             CF    1875            WILDE

[119 rows x 4 columns]

Evidentemente `loc_part` toma distritos del conurbano y no solamente la Capital Federal. Ver esto en la Documentacoin porque es distinto a como lo clasifica la API.

In [22]:
df2.loc[df2.provincia_part == 'CF'].loc_part.unique()

array([nan, '-1', 'AVELLANEDA', 'BANFIELD', 'BARILOCHE', 'BERAZATEGUI',
       'BERNAL', 'CABA', 'CABA RETIRO', 'CAMPANA', 'CAP FED', 'CAPITAL',
       'CAPITAL -LA RIOJA-', 'CAPITAL FEDERAL', 'CASEROS', 'CASTELAR',
       'CASTELLAR', 'CATAMARCA', 'CDAD AUTONOMA BS AS', 'CIUDAD MADERO',
       'CIUDADELA', 'COMODORO RIVADAVIA', 'CORDOBA', 'CUERPO 2',
       'DEL VISO', 'DTO 308', 'EXALTACION DE LA CRU', 'FLORIDA',
       'FORMOSA', 'FRANCISCO ALVAREZ', 'GONZALEZ CATAN', 'HAEDO',
       'HURLINGHAN', 'ITUZAINGO', 'JOSE LEON SUAREZ', 'KM 45',
       'LA FLORIDA', 'LA MATANZA', 'LA UNION', 'LANUS', 'LANUS ESTE',
       'LANUS OESTE', 'LOMAS DE ZAMORA', 'LOMAS DEL MIRADOR', 'LUJAN',
       'MALAVER', "MAR DEL P'LATA", 'MAR DEL PLATA', 'MARCOS PAZ',
       'MARIANO BENITEZ PERG', 'MARTINEZ', 'MERCEDES', 'MINA CLAVERO',
       'MORON', 'NAVARRO', 'OLIVOS', 'PABLO NOGUES', 'PALOMAR', 'PIGUE',
       'PINAMAR', 'POMPEYA', 'QUILMES', 'QUILMES OESTE', 'RAMOS MEJIA',
       'REMEDIOS DE ESCALADA

Evidentemente los datos no estan muy limpios. 
Si bien casi todos los distritos pertenecen al Conurbano, hay lugares como Bariloche, Cordoba, Mar del Plata, Santa Fe. Consultar:
- CF incluye al Conurbano?
- Por que los datos no son coherentes?

---

### Intentar popular una base con los datos solicitados

In [23]:
df_loc =  df2.groupby(['loc_part', 'provincia_part']).count().copy()
df_loc.reset_index(inplace = True)
df_loc.head(10)

loc_part provincia_part  nacionalidad  cp_part
0   VENEZUELA Y PERU             BA             1        1
1                 -1             BA             2        2
2                 -1             CF             1        1
3                 -1             SJ             1        1
4                 -1             SL             2        2
5              10064             BA             2        2
6       12 DE AGOSTO             BA             2        2
7      12 DE OCTUBRE             BA             2        2
8        16 DE JULIO             BA             2        2
9       17 DE AGOSTO             BA             1        1

In [24]:
df_loc.loc_part.unique()  # Exploremos los diferentes localidades

array([' VENEZUELA Y PERU', '-1', '10064', '12 DE AGOSTO',
       '12 DE OCTUBRE', '16 DE JULIO', '17 DE AGOSTO', '20 DE JUNIO',
       '25 DE MAYO', '3 DE FEBRERO', '30 DE AGOSTO', '9 DE ABRIL',
       '9 DE JULIO', 'ABASTO', 'ACASSUSO', 'ADROGUE',
       'ADROGUE-ALTE BROWN', 'AEROPUERTO EZEIZA', 'AGOTE',
       'AGUAS CORRIENTES', 'AGUSTINA', 'ALBARRACIN', 'ALBERTI',
       'ALDO BONZI', 'ALEJANDRO KORN', 'ALEJANDRO PETION', 'ALICIA',
       'ALMIRANTE BROWN', 'ALSINA', 'ALUMINE', 'ALVEAR', 'AMERICA UNIDA',
       'ARRECIFES', 'AVELLANEDA', 'AYACUCHO', 'AZUL', 'Avellaneda',
       'BAHIA BLANCA', 'BALCARCE', 'BANFIELD', 'BARADERO', 'BARILOCHE',
       'BARRIO PARQUE LELOIR', 'BASAVILBASO', 'BECCAR',
       'BELEN DE ESCOBAR', 'BELLA VISTA', 'BENAVIDEZ', 'BERAZATEGUI',
       'BERISSO', 'BERNAL', 'BERNAL ESTE', 'BERNAL OESTE', 'BOLIVAR',
       'BOSCH', 'BOSQUES', 'BOULOGNE', 'BRAGADO', 'BUENO AIRES',
       'BUENOS AIRES', 'BURZACO', 'Baradero', 'Boulogne',
       'C.J.EL PALOMAR', 

Deberia eliminarse los primeros 5 rows dado que los valores son muy anomalos. 
Ademas abria que ver de eliminar `10064` 

In [66]:
# Script corte y quizas ineficiente para 
df_loc['centroide_lat'] = None
df_loc['centroide_lon'] = None
df_loc['departamento_nombre'] = None
df_loc['municipio_nombre'] = None
df_loc['localidad_nombre'] = None
df_loc['provincia_de_API'] = None

In [67]:
for r in df_loc.index:
    datos = geo.get_centroides('localidades', df_loc.loc_part[r], max = 1, aplanar = True)
    if len(datos) == 0:  # El flow es asi: Si no encuentra localidad, busca por municipio y sino por departamento
        datos = geo.get_centroides('municipios', df_loc.loc_part[r], max = 1, aplanar = True)
        
        if len(datos) == 0: 
            datos = geo.get_centroides('departamentos', df_loc.loc_part[r], max = 1, aplanar = True)
            
            if len(datos) == 0:
                print (f'{df_loc.loc_part[r]} == NULL')
                continue
                
            else:  # Departamento
                try:
                    df_loc.loc[r,'centroide_lat'] = datos[0]['centroide_lat']
                    df_loc.loc[r,'centroide_lon'] = datos[0]['centroide_lon']
                    df_loc.loc[r,'departamento_nombre'] = datos[0]['nombre']
                    df_loc.loc[r,'provincia_de_API'] = datos[0]['provincia_nombre']
                except: pass

        else:  # Municipio
            try:
                df_loc.loc[r,'centroide_lat'] = datos[0]['centroide_lat']
                df_loc.loc[r,'centroide_lon'] = datos[0]['centroide_lon']
                df_loc.loc[r,'provincia_de_API'] = datos[0]['provincia_nombre']
                df_loc.loc[r,'departamento_nombre'] = datos[0]['departamento_nombre']
                df_loc.loc[r,'municipio_nombre'] = datos[0]['nombre']
            except: pass
    else:  #Localidad
        try: 
            df_loc.loc[r,'centroide_lat'] = datos[0]['centroide_lat']
            df_loc.loc[r,'centroide_lon'] = datos[0]['centroide_lon']
            df_loc.loc[r,'provincia_de_API'] = datos[0]['provincia_nombre']
            df_loc.loc[r,'departamento_nombre'] = datos[0]['departamento_nombre']
            df_loc.loc[r,'municipio_nombre'] = datos[0]['municipio_nombre']
            df_loc.loc[r,'localidad_nombre'] = datos[0]['nombre']
        except: pass

Arriba se pueden ver todos los casos en los que hubo errores nulos

In [71]:
df_loc.shape

(699, 10)

In [69]:
df_loc.localidad_nombre.isna().sum()

0

Sobre la totalidad de opciones unicas agrupadas como localidad + provincia (699), 115 opciones no se encontraron. Esto puede verse mas abajo donde la informacion no es consistente o el nombre de la localidad y la provincia. A su vez, hay que corregir manualmente el input `ciudad de buenos aires` para capital. 
Para esta querry no utilice el campo de provincia del dataset original dado que es inconsistente.


In [99]:
pd.set_option('display.max_rows', 800)  # Para ver todas las filas
df_loc

loc_part provincia_part  nacionalidad  cp_part centroide_lat  \
0        VENEZUELA Y PERU             BA             1        1          None   
1                      -1             BA             2        2      -31.3069   
2                      -1             CF             1        1      -31.3069   
3                      -1             SJ             1        1      -31.3069   
4                      -1             SL             2        2      -31.3069   
5                   10064             BA             2        2          None   
6            12 DE AGOSTO             BA             2        2          None   
7           12 DE OCTUBRE             BA             2        2      -35.6077   
8             16 DE JULIO             BA             2        2      -37.2021   
9            17 DE AGOSTO             BA             1        1      -37.9087   
10            20 DE JUNIO             BA             2        2      -34.7855   
11             25 DE MAYO             BA             2        2      -35.4339   
12           3 DE FEBRERO             BA             1        1          None   
13           30 DE AGOSTO             BA             1        1       -36.278   
14             9 DE ABRIL             BA             2        2      -34.7565   
15             9 DE JULIO             BA             2        2      -35.4447   
16                 ABASTO             BA             2        2      -35.0104   
17               ACASSUSO             BA             2        2      -34.4794   
18                ADROGUE             BA             2        2      -34.8016   
19     ADROGUE-ALTE BROWN             BA             1        1          None   
20      AEROPUERTO EZEIZA             BA             1        1      -34.8128   
21                  AGOTE             BA             2        2          None   
22       AGUAS CORRIENTES             BA             1        1          None   
23               AGUSTINA             BA             1        1      -34.4607   
24             ALBARRACIN             SJ             1        1      -31.4936   
25                ALBERTI             BA             2        2      -35.0331   
26             ALDO BONZI             BA             2        2      -34.7142   
27         ALEJANDRO KORN             BA             2        2      -35.0135   
28       ALEJANDRO PETION             BA             2        2      -34.9794   
29                 ALICIA             CA             1        1      -31.9387   
30        ALMIRANTE BROWN             BA             2        2      -31.3076   
31                 ALSINA             BA             2        2      -33.9096   
32                ALUMINE             NE             2        2      -39.2395   
33                 ALVEAR             CO             1        1      -29.0986   
34          AMERICA UNIDA             BA             1        1      -34.8862   
35              ARRECIFES             BA             2        2      -34.0646   
36             AVELLANEDA             BA             2        2      -34.6627   
37             AVELLANEDA             CF             2        2      -34.6627   
38             AVELLANEDA             SF             2        2      -34.6627   
39               AYACUCHO             BA             1        1      -37.1537   
40                   AZUL             BA             2        2      -36.7795   
41             Avellaneda             BA             1        1      -34.6627   
42           BAHIA BLANCA             BA             2        2      -38.7114   
43               BALCARCE             BA             2        2      -37.8483   
44               BANFIELD             BA             2        2      -34.7379   
45               BANFIELD             CF             1        1      -34.7379   
46               BARADERO             BA             2        2      -33.8129   
47              BARILOCHE             BA             2        2      -41.1369   
48              BARILOCHE             CF        

In [32]:
df_loc.groupby('departamento_nombre').count().sort_values('loc_part', ascending = False)

loc_part provincia_part  nacionalidad  cp_part centroide_lat  \
0     VENEZUELA Y PERU             BA             1        1      -33.4395   
1                   -1             BA             2        2      -33.4395   
2                   -1             CF             1        1      -33.4395   
3                   -1             SJ             1        1      -33.4395   
4                   -1             SL             2        2      -33.4395   
..                 ...            ...           ...      ...           ...   
694            ZAVALIA             BA             2        2      -33.4395   
695             ZELAYA             BA             2        2      -33.4395   
696  capilla del señor             BA             1        1      -33.4395   
697           martinez             BA             1        1      -33.4395   
698         san isidro             BA             1        1      -33.4395   

    centroide_lon departamento_nombre municipio_nombre localidad_nombre  \
0        -64.8317          Río Cuarto             Suco             SUCO   
1        -64.8317          Río Cuarto             Suco             SUCO   
2        -64.8317          Río Cuarto             Suco             SUCO   
3        -64.8317          Río Cuarto             Suco             SUCO   
4        -64.8317          Río Cuarto             Suco             SUCO   
..            ...                 ...              ...              ...   
694      -64.8317          Río Cuarto             Suco             SUCO   
695      -64.8317          Río Cuarto             Suco             SUCO   
696      -64.8317          Río Cuarto             Suco             SUCO   
697      -64.8317          Río Cuarto             Suco             SUCO   
698      -64.8317          Río Cuarto             Suco             SUCO   

    provincia_de_API  
0            Córdoba  
1            Córdoba  
2            Córdoba  
3            Córdoba  
4            Córdoba  
..               ...  
694          Córdoba  
695          Córdoba  
696          Córdoba  
697          Córdoba  
698          Córdoba  

[699 rows x 10 columns]

---

# Probando usar CPA para terminar de ubicar missing data

Cree una base de datos usando informacion externa para obtener las localidades de todos los CPA de la Republica Argentina. La misma se encuentra en [GitHub](link)

In [19]:
import sqlalchemy
engine = sqlalchemy.create_engine('sqlite:///SQL/CPA.db')
con = engine.connect()

In [20]:
con.execute('select * from provincia limit 10').fetchall() #Probar si conecto a la base

[(1, 'Ciudad Autónoma de Buenos Aires (CABA)', 'AR-C'),
 (2, 'Buenos Aires', 'AR-B'),
 (3, 'Catamarca', 'AR-K'),
 (4, 'Córdoba', 'AR-X'),
 (5, 'Corrientes', 'AR-W'),
 (6, 'Entre Ríos', 'AR-E'),
 (7, 'Jujuy', 'AR-Y'),
 (8, 'Mendoza', 'AR-M'),
 (9, 'La Rioja', 'AR-F'),
 (10, 'Salta', 'AR-A')]

cpa_pro = pd.read_sql('provincia', con = con)
cpa_pro.head(5)

In [22]:
cpa_loc = pd.read_sql('localidad', con = con)
cpa_loc.head(5)

C:\Users\joaqu\Anaconda3\lib\site-packages\sqlalchemy\dialects\sqlite\base.py:1719: SAWarning: Could not instantiate type <class 'sqlalchemy.sql.sqltypes.INTEGER'> with reflected arguments ['10']; using no arguments.
  % (coltype, args)
C:\Users\joaqu\Anaconda3\lib\site-packages\sqlalchemy\dialects\sqlite\base.py:1719: SAWarning: Could not instantiate type <class 'sqlalchemy.sql.sqltypes.SMALLINT'> with reflected arguments ['6']; using no arguments.
  % (coltype, args)


l_id  provincia_id                 nombre  codigopostal
0     1            13      CABEZA DE CHANCHO          3061
1     2            13            CAMPO GARAY          3066
2     3            13         CAMPO SAN JOSE          3060
3     4            13  COLONIA INDEPENDENCIA          3066
4     5            13     COLONIA MONTEFIORE          2341

###### cpa_all = cpa_loc.merge(cpa_pro, left_on='provincia_id', right_on='p_id', suffixes=['_localidad','_provincia'])
cpa_all.sample(10)

In [24]:
cpa_all.loc[cpa_all.codigopostal == 0]

l_id  provincia_id nombre_localidad  codigopostal  p_id  \
3059  2755             1         C.A.B.A.             0     1   

                            nombre_provincia codigo31662  
3059  Ciudad Autónoma de Buenos Aires (CABA)        AR-C

Sacar codigo postal = 0  (Capital Federal) este data frame. Para capital usaremos otra tabla.


In [25]:
# Chequear por provincia
cpa_all.groupby(['nombre_provincia']).count().sort_values(by= 'provincia_id', ascending = False)

l_id  provincia_id  nombre_localidad  \
nombre_provincia                                                               
Santiago del Estero                     2432          2432              2432   
Tucumán                                 2203          2203              2203   
Buenos Aires                            2117          2117              2117   
Córdoba                                 1979          1979              1979   
Mendoza                                 1483          1483              1483   
Corrientes                              1293          1293              1293   
Salta                                   1251          1251              1251   
San Luis                                1230          1230              1230   
Entre Ríos                              1116          1116              1116   
Catamarca                                967           967               967   
Santa Fe                                 942           942               942   
San Juan                                 874           874               874   
Jujuy                                    733           733               733   
Chaco                                    710           710               710   
La Pampa                                 702           702               702   
Formosa                                  553           553               553   
Misiones                                 508           508               508   
La Rioja                                 489           489               489   
Neuquén                                  426           426               426   
Río Negro                                331           331               331   
Chubut                                   323           323               323   
Santa Cruz                               209           209               209   
Tierra del Fuego                          91            91                91   
Ciudad Autónoma de Buenos Aires (CABA)     1             1                 1   

                                        codigopostal  p_id  codigo31662  
nombre_provincia                                                         
Santiago del Estero                             2432  2432         2432  
Tucumán                                         2203  2203         2203  
Buenos Aires                                    2117  2117         2117  
Córdoba                                         1979  1979         1979  
Mendoza                                         1483  1483         1483  
Corrientes                                      1293  1293         1293  
Salta                                           1251  1251         1251  
San Luis                                        1230  1230         1230  
Entre Ríos                                      1116  1116         1116  
Catamarca                                        967   967          967  
Santa Fe                                         942   942          942  
San Juan                                         874   874          874  
Jujuy                                            733   733          733  
Chaco                                            710   710          710  
La Pampa                                         702   702          702  
Formosa                                          553   553          553  
Misiones                                         508   508          508  
La Rioja                                         489   489          489  
Neuquén                                          426   426          426  
Río Negro                                        331   331          331  
Chubut                                           323   323          323  
Santa Cruz                                       209   209          209  
Tierra del Fuego                                  91    91           91  
Ciudad Autónoma de Buenos Aires (CABA)             1     1            1

Evidentemente hay un error y/o la base se encuentra incompleta dado que no hay codigos para CABA. Intentare rellenar una base con los mismos
usando los links anteriormente mencionados

In [26]:
cpa_all.loc[cpa_all.nombre_localidad == 'OLIVOS'] # Palermo

l_id  provincia_id nombre_localidad  codigopostal  p_id  \
3000  17298             2           OLIVOS          1636     2   

     nombre_provincia codigo31662  
3000     Buenos Aires        AR-B

Una vez resuelto esto deberiamos ver que casos tenemos nulos e intentar popularlos.
Para eso vamos a seguir cuatro pasos:<br>
1) Ubicar `None` values en la columna localidad del dataframe (`df_loc`) y tomar ese CPA.<br>
2) Buscar en la tabla `cpa_all` a que localidad corresponde ese CPA.<br>
3) Buscar los datos de geolocalizacion en la API de georefar<br>
4) Agregar esos datos nuevamente a la tabla.

## Corriendo la repopulacion

In [18]:
df_missing = df_loc.loc[df_loc.localidad_nombre.isna()].copy() #vamos a conservar los index para rellenar la df_loc

NameError: name 'df_loc' is not defined

In [159]:
df_missing.groupby('provincia_part').count()

loc_part  nacionalidad  cp_part  centroide_lat  centroide_lon  \
provincia_part                                                                  
BA                    90            90       90              5              5   
CA                     1             1        1              0              0   
CB                     1             1        1              0              0   
CF                    17            17       17              2              2   
ER                     2             2        2              0              0   
MZ                     1             1        1              0              0   
NE                     1             1        1              1              1   
SC                     1             1        1              0              0   
SF                     1             1        1              0              0   

                departamento_nombre  municipio_nombre  localidad_nombre  \
provincia_part                                                            
BA                                0                 0                 0   
CA                                0                 0                 0   
CB                                0                 0                 0   
CF                                0                 0                 0   
ER                                0                 0                 0   
MZ                                0                 0                 0   
NE                                0                 0                 0   
SC                                0                 0                 0   
SF                                0                 0                 0   

                provincia_de_API  
provincia_part                    
BA                             5  
CA                             0  
CB                             0  
CF                             2  
ER                             0  
MZ                             0  
NE                             1  
SC                             0  
SF                             0

La mayoria de los valores faltantes sonn de Buenos Aires y Capital. Deberiamos juntar estos CP antes de proseguir.

In [162]:
df_missing.loc[df_missing.provincia_de_API.notna()]

loc_part provincia_part  nacionalidad  cp_part centroide_lat  \
193    ESTEBAN ECHEVERRIA             BA             2        2      -34.8312   
194   EXALTACION DE LA CR             BA             2        2      -34.2951   
195  EXALTACION DE LA CRU             BA             1        1      -34.2951   
196  EXALTACION DE LA CRU             CF             1        1      -34.2951   
304            LA MATANZA             BA             2        2      -34.7702   
305            LA MATANZA             CF             1        1      -34.7702   
545   SAN MARTIN DE LOS A             NE             2        2      -40.1348   
596       TRES DE FEBRERO             BA             2        2       -34.596   

    centroide_lon departamento_nombre municipio_nombre localidad_nombre  \
193       -58.477                None             None             None   
194      -59.1559                None             None             None   
195      -59.1559                None             None             None   
196      -59.1559                None             None             None   
304      -58.6254                None             None             None   
305      -58.6254                None             None             None   
545      -71.3015                None             None             None   
596      -58.5791                None             None             None   

    provincia_de_API  
193     Buenos Aires  
194     Buenos Aires  
195     Buenos Aires  
196     Buenos Aires  
304     Buenos Aires  
305     Buenos Aires  
545          Neuquén  
596     Buenos Aires

## Creando base de Datos para CABA

In [27]:
import csv
with open('./SQL/capital_cp.csv', newline='', encoding='utf-8') as f: #el archivo contiene datos scrapeados de https://www.barriorecoleta.com.ar/blog/codigos-postales/
    reader = csv.reader(f)
    data = list(reader)

In [28]:
capital_df = pd.DataFrame(columns = ['barrio', 'comuna_numero', 'codigo_postal'])

In [29]:
for barrio in data:
    for cp in barrio[2:]:
        capital_df = capital_df.append({'barrio' : barrio[0], 'comuna_numero' : barrio[1], 'codigo_postal' : cp} , ignore_index=True)
                       

In [30]:
capital_df.sample(5)  # Anda bien

barrio comuna_numero codigo_postal
164             Barracas             4          1153
158             Barracas             4          1138
563  Villa General Mitre            11          1406
444        San Cristóbal             3          1230
112            Balvanera             3          1083

El CP no es unico para un barrio o comuna. Atencion a esto! esto es coherente con la informacion consultada

In [31]:
capital_df.to_csv('./SQL/capital_formatted.csv')

Una vez que obtuve esta base la agregue a un script de SQL y la agregue a la base `CPA.db`

In [32]:
con = engine.connect()
capital_cp = pd.read_sql('comunas_capital', con=con)

C:\Users\joaqu\Anaconda3\lib\site-packages\sqlalchemy\dialects\sqlite\base.py:1719: SAWarning: Could not instantiate type <class 'sqlalchemy.sql.sqltypes.INTEGER'> with reflected arguments ['2']; using no arguments.
  % (coltype, args)


In [33]:
capital_cp.loc[capital_cp.codigopostal == 1414]

c_id  provincia_id            barrio  comuna  codigopostal
56     56             1          Recoleta       2          1414
75     75             1           Palermo      14          1414
242   242             1         Chacarita      15          1414
250   250             1        Colegiales      13          1414
548   548             1      Villa Crespo      15          1414
553   553             1  Villa del Parque      11          1414
580   580             1        Villa Real      10          1414
596   596             1         Caballito       6          1414

In [34]:
capital_cp.sample(5)

c_id  provincia_id         barrio  comuna  codigopostal
451   451             1  San Cristóbal       3          1244
286   286             1   Constitución       1          1159
34     34             1       Recoleta       2          1119
388   388             1       Paternal      15          1427
600   600             1         Flores       7          1407

In [35]:
df_completo = cpa_all.merge(capital_cp, on='provincia_id',how='left')

In [36]:
df_completo.loc[(df_completo.provincia_id == 1) | (df_completo.provincia_id == 2) ]

l_id  provincia_id nombre_localidad  codigopostal_x  p_id  \
942    878             2       AVELLANEDA            1870     2   
943    879             2        CRUCESITA            1870     2   
944    880             2         DOCK SUD            1871     2   
945    881             2          SARANDI            1872     2   
946    882             2   VILLA DOMINICO            1874     2   
...    ...           ...              ...             ...   ...   
3680  2755             1         C.A.B.A.               0     1   
3681  2755             1         C.A.B.A.               0     1   
3682  2755             1         C.A.B.A.               0     1   
3683  2755             1         C.A.B.A.               0     1   
3684  2755             1         C.A.B.A.               0     1   

                            nombre_provincia codigo31662   c_id  \
942                             Buenos Aires        AR-B    NaN   
943                             Buenos Aires        AR-B    NaN   
944                             Buenos Aires        AR-B    NaN   
945                             Buenos Aires        AR-B    NaN   
946                             Buenos Aires        AR-B    NaN   
...                                      ...         ...    ...   
3680  Ciudad Autónoma de Buenos Aires (CABA)        AR-C  621.0   
3681  Ciudad Autónoma de Buenos Aires (CABA)        AR-C  622.0   
3682  Ciudad Autónoma de Buenos Aires (CABA)        AR-C  623.0   
3683  Ciudad Autónoma de Buenos Aires (CABA)        AR-C  624.0   
3684  Ciudad Autónoma de Buenos Aires (CABA)        AR-C  625.0   

               barrio  comuna  codigopostal_y  
942               NaN     NaN             NaN  
943               NaN     NaN             NaN  
944               NaN     NaN             NaN  
945               NaN     NaN             NaN  
946               NaN     NaN             NaN  
...               ...     ...             ...  
3680     Villa Lugano     8.0          1439.0  
3681  Villa Riachuelo     8.0          1439.0  
3682    Villa Soldati     8.0          1406.0  
3683    Villa Soldati     8.0          1407.0  
3684    Villa Soldati     8.0          1437.0  

[2743 rows x 11 columns]

La base esta completa y funcionando.

## A la base original le voy a agregar los campos nombre_localidad, provincia_id, nombre_provincia, barrio y comuna.

In [37]:
# un set con los CP en Capital Federal
set_capital = set(capital_cp.codigopostal)
set_capital.intersection(set(cpa_all.codigopostal)) #no se solapa con los CP de provincia. Esto es coherente con la informacion que tenemos

set()

In [38]:
df2.loc[df2.cp_part == '0'].shape # 100 rows sin CP y sin provincia. Estos seran adivinados

(100, 4)

In [39]:
df2.loc[df2.cp_part == '0'].head()

nacionalidad provincia_part cp_part         loc_part
4            AR            NaN       0       9 DE ABRIL
9            AR            NaN       0  ALMIRANTE BROWN
10           AR            NaN       0           ALSINA
17           AR            NaN       0           BECCAR
23           AR            NaN       0      BERNAL ESTE

In [40]:
df2.cp_part.isna().sum() # No hay missing values

0

Chequear cuantos CP corresponden a una unica provincia y unica localidad

In [61]:
cpa_all.groupby(['codigopostal', 'nombre_provincia']).count().sort_values( by = 'p_id', ascending = False)

l_id  provincia_id  nombre_localidad  p_id  \
codigopostal nombre_provincia                                                  
5590         Mendoza               204           204               204   204   
5569         Mendoza               196           196               196   196   
4178         Tucumán               151           151               151   151   
4119         Tucumán               149           149               149   149   
5467         San Juan              139           139               139   139   
...                                ...           ...               ...   ...   
5000         Córdoba                 1             1                 1     1   
4709         Catamarca               1             1                 1     1   
1601         Buenos Aires            1             1                 1     1   
4613         Santiago del Estero     1             1                 1     1   
9421         Tierra del Fuego        1             1                 1     1   

                                  codigo31662  
codigopostal nombre_provincia                  
5590         Mendoza                      204  
5569         Mendoza                      196  
4178         Tucumán                      151  
4119         Tucumán                      149  
5467         San Juan                     139  
...                                       ...  
5000         Córdoba                        1  
4709         Catamarca                      1  
1601         Buenos Aires                   1  
4613         Santiago del Estero            1  
9421         Tierra del Fuego               1  

[2005 rows x 5 columns]

In [62]:
provincia_por_cp = cpa_all.groupby('codigopostal')['nombre_provincia'].nunique()
provincia_por_cp.loc[provincia_por_cp > 1].count() 

100

In [63]:
# Hay 100 codigos postales que comparten diferentes provincias

In [64]:
cpa_all.loc[cpa_all.codigopostal == 9420].head() #Ejemplo

l_id  provincia_id nombre_localidad  codigopostal  p_id  \
3076  2772            24        EL PARAMO          9420    24   
3077  2773            24       RIO GRANDE          9420    24   
3078  2774            24    SAN SEBASTIAN          9420    24   
3079  2775            24       SANTA INES          9420    24   
3080  2776            24          TOLHUIN          9420    24   

      nombre_provincia codigo31662  
3076  Tierra del Fuego        AR-V  
3077  Tierra del Fuego        AR-V  
3078  Tierra del Fuego        AR-V  
3079  Tierra del Fuego        AR-V  
3080  Tierra del Fuego        AR-V

In [65]:
cp_prov_no_unicos = set(provincia_por_cp.loc[provincia_por_cp > 1].index)
len(cp_prov_no_unicos)

100

In [66]:
localidad_por_cp = cpa_all.groupby('codigopostal')['nombre_localidad'].nunique()

In [67]:
cp_loc_no_unicos = set(localidad_por_cp.loc[localidad_por_cp > 1].index )
len (cp_loc_no_unicos)

1632

In [68]:
len(cp_loc_no_unicos.intersection(cp_prov_no_unicos))  # Evidentemente si hay 100 codigos que coparten provincia, es esperable que todos los cp que comparten distintas localidades
                                                       # esten incluidos. Sanity check.

100

---

Ahora con Capital Federal

In [69]:
cpa_all.groupby('codigopostal')['nombre_localidad'].nunique().sort_values(ascending=False) # Vemos como CP no siempre asigna un nombre de localidad tampoco.

codigopostal
5590    204
5569    195
4178    151
4119    140
5539    138
       ... 
4709      1
5000      1
5012      1
5014      1
0         1
Name: nombre_localidad, Length: 1901, dtype: int64

In [70]:
localidad_por_cp = cpa_all.groupby('codigopostal')['nombre_localidad'].nunique()
cp_localidad_no_unicos = set(localidad_por_cp.loc[localidad_por_cp > 1].index) 

In [71]:
len(cp_localidad_no_unicos) # 1636 cp que no corresponden a un unico municipio.

1632

Ahora con capital

In [72]:
Capital_barrio_por_cp = capital_cp.groupby('codigopostal')['barrio'].nunique()

In [73]:
capital_cp_barrio_no_unicos = set(Capital_barrio_por_cp.loc[Capital_barrio_por_cp > 1].index)
len(capital_cp_barrio_no_unicos)

159

In [74]:
len(set(Capital_barrio_por_cp.loc[Capital_barrio_por_cp == 1].index))  # Hay 159 CP que no corresponden a un unico barrio

144

In [75]:
Capital_comuna_por_CP = capital_cp.groupby('codigopostal')['comuna'].nunique()
capital_cp_comuna_no_unicos = set(Capital_comuna_por_CP.loc[Capital_comuna_por_CP > 1].index)

In [76]:
len(capital_cp_comuna_no_unicos) # Hay 119 CP que no corresponden a una unica comuna

119

In [77]:
len(set(Capital_comuna_por_CP.loc[Capital_comuna_por_CP == 1].index))

184

In [78]:
len(capital_cp_barrio_no_unicos.intersection(capital_cp_comuna_no_unicos)) #Logicamente si un CP se usa en otra Comuna entonces hay otro barrio con el mismo CP.

119

---

# Algoritmo

1) Ver si es de provincia o capital
- 1.1) Si es de Capital ver si CP corresponde a barrio unico. Si es asi se asigna Localidad , Comuna [departamento] y Provincia<br>
-  1.2) Si no corresponde a barrio unico se checa si el CP corresponde a unica comuna. Si es asi se asigna solo comuna y Provincia.Sino solo se asigna Provincia Capital Federal.<br>
- 1.3) Si es de provincia se checa si el CP corresponde a una unica localidad. Si es asi se asigna localidad y Provincia.<br>
- 1.4) Si no corresponde a una unica localidad se checa si el CP corresponde a una unica provincia. Si es asi se asgina solo Provincia. Sino no se asigna ningun valor.<br>

2) Usando la tabla modificada se correra la funcion geo.get_centroides con las siguientes reglas:<br>
- 2.1) Si hay provincia registrada se ingresa a la funcion.<br>
- 2.1.1) Si hay localidad se ingresa a la funcion. Se obtiene el centroide para la localidad.<br>
- 2.1.2) Si no hay localidad habra dos opciones, dependiendo si es de Capital o Provincia:<br>
- -      Provincia) Se usa la provincia como campo y se usa el campo `loc_part` (ingresado por el usuario). Si encuentra se agrega la localidad. Sino se agrega centroide de la provincia.<br>
- -     Capital) Se usa la comuna si la hay y se busca por departamento. Sino se usa el campo 'loc_part' como localidad. Es probabable que no devuelva dato por lo que solo se agrega centroide de Capital Federal. Si devuelve datos se agrega la comuna y no la localidad.<br>
- 2.2) Si no hay provincia registrada se usa el campo `loc_pat`.
    

In [79]:
df2.head(3)

nacionalidad provincia_part cp_part      loc_part
0           AR            NaN    1704           NaN
1           AR            NaN    1704           NaN
2           AR            NaN    1688  12 DE AGOSTO

In [80]:
augmented_df = df2.copy()
augmented_df['provincia_por_cp']= None
augmented_df['localidad_por_cp']= None
augmented_df['departamento_por_cp']= None
augmented_df.head(3)

nacionalidad provincia_part cp_part      loc_part provincia_por_cp  \
0           AR            NaN    1704           NaN             None   
1           AR            NaN    1704           NaN             None   
2           AR            NaN    1688  12 DE AGOSTO             None   

  localidad_por_cp departamento_por_cp  
0             None                None  
1             None                None  
2             None                None

In [81]:
set_provincia = set(cpa_all.codigopostal)
set_provincia.remove(0) # Removemos el codigo postal 0
len(set_provincia)

1900

In [82]:
def infer_provincia(cp):
    if int(cp) in set_capital:
        return 'CIUDAD AUTONOMA DE BUENOS AIRES'
    if int(cp) in set_provincia:
        if  int(cp) in cp_prov_no_unicos:
            return  'NO UNICA PROVINCIA'
        else:
            prov = cpa_all.loc[cpa_all.codigopostal == int(cp)].nombre_provincia.unique()
            return prov[0].upper()
    if (int(cp) not in set_provincia and int(cp) not in set_capital):
        return 'CP INDEFINIDO'
    if cp.isna() or int(cp) == 0:
        return 'CP INDEFINIDO'

def infer_localidad(cp):
    cp = int(cp)
    if cp in set_capital:
        if cp in capital_cp_barrio_no_unicos:
                return 'NO UNICA LOCALIDAD'
        else:
            localidad = capital_cp.loc[capital_cp.codigopostal == cp].barrio.unique()[0]
            return localidad.upper()
    if cp in set_provincia:
        if cp in cp_localidad_no_unicos:
            return 'NO UNICA LOCALIDAD'
        else:
            localidad = cpa_all.loc[cpa_all.codigopostal == cp].nombre_localidad.unique()[0]
            return localidad.upper()
    if cp not in set_provincia and cp not in set_capital:
        return 'CP INDEFINIDO'
    
def infer_departamento(cp):
    cp = int(cp)
    if cp in set_capital:
        if cp in capital_cp_barrio_no_unicos:
            return 'NO UNICO DEPARTAMENTO'
        else:
            departamento = capital_cp.loc[capital_cp.codigopostal == cp].comuna.unique()
            return f'COMUNA {departamento[0]}'

In [83]:
# Provincia
augmented_df['provincia_por_cp'] = augmented_df.cp_part.apply(infer_provincia)

In [84]:
augmented_df.sample(10)

nacionalidad provincia_part cp_part             loc_part  \
668            AR             BA    1766             LA TRIBU   
240            AR            NaN    1754            SAN JUSTO   
150            AR            NaN    1752    LOMAS DEL MIRADOR   
775            AR             BA    1831          MONTEGRANDE   
625            AR             BA    1846          José Marmol   
621            AR             BA    1714            ITUZAINGO   
588            AR             BA    1752  GREGORIO DE LA FERR   
1112           AR             CB    1181                 CABA   
413            AR             BA    2812    CAPILLA DEL SEÑOR   
509            AR             BA    1618             EL TALAR   

                     provincia_por_cp localidad_por_cp departamento_por_cp  
668                      BUENOS AIRES             None                None  
240                      BUENOS AIRES             None                None  
150                      BUENOS AIRES             None                None  
775                     CP INDEFINIDO             None                None  
625                      BUENOS AIRES             None                None  
621                      BUENOS AIRES             None                None  
588                      BUENOS AIRES             None                None  
1112  CIUDAD AUTONOMA DE BUENOS AIRES             None                None  
413                      BUENOS AIRES             None                None  
509                      BUENOS AIRES             None                None

In [85]:
# Localidad
augmented_df['localidad_por_cp'] = augmented_df.cp_part.apply(infer_localidad)
augmented_df.sample(5)

nacionalidad provincia_part cp_part             loc_part  \
970            AR             BA    1667          TORTUGUITAS   
927            AR             BA    1650  SAN MARTIN DE TOURS   
394            AR             BA    1638          BUENO AIRES   
906            AR             BA    1646         SAN FERNANDO   
1111           AR             CA    5900          VILLA MARIA   

     provincia_por_cp    localidad_por_cp departamento_por_cp  
970      BUENOS AIRES  NO UNICA LOCALIDAD                None  
927      BUENOS AIRES  GENERAL SAN MARTIN                None  
394      BUENOS AIRES       VICENTE LOPEZ                None  
906      BUENOS AIRES  NO UNICA LOCALIDAD                None  
1111          CÓRDOBA  NO UNICA LOCALIDAD                None

In [86]:
augmented_df.loc[augmented_df.localidad_por_cp != 'NO UNICA LOCALIDAD'].sample(10)

nacionalidad provincia_part cp_part         loc_part provincia_por_cp  \
323            AR             BA    1641         ACASSUSO    CP INDEFINIDO   
499            AR             BA    1611     DON TORCUATO     BUENOS AIRES   
1204           CN             CF    1708            MORON     BUENOS AIRES   
65             AR            NaN       0        DON BOSCO    CP INDEFINIDO   
664            AR             BA    1774        LA SALADA     BUENOS AIRES   
751            AR             BA    1723   MARIANO ACOSTA     BUENOS AIRES   
496            PY             BA    1984        DOMSELAAR     BUENOS AIRES   
296            AR            NaN    1875            WILDE     BUENOS AIRES   
1028           AR             BA    1772     VILLA CLELIA    CP INDEFINIDO   
1246           AR             CF    1709  VILLA SARMIENTO    CP INDEFINIDO   

     localidad_por_cp departamento_por_cp  
323     CP INDEFINIDO                None  
499      DON TORCUATO                None  
1204            MORON                None  
65      CP INDEFINIDO                None  
664         LA SALADA                None  
751    MARIANO ACOSTA                None  
496         DOMSELAAR                None  
296             WILDE                None  
1028    CP INDEFINIDO                None  
1246    CP INDEFINIDO                None

In [87]:
# Departamento
augmented_df['departamento_por_cp'] = augmented_df.cp_part.apply(infer_departamento)
augmented_df.sample(5)

nacionalidad provincia_part cp_part             loc_part provincia_por_cp  \
447           AR             BA    1684  CDAD AUTONOMA BS AS     BUENOS AIRES   
717           AR             BA    1613       LOS POLVORINES     BUENOS AIRES   
17            AR            NaN       0               BECCAR    CP INDEFINIDO   
824           AR             BA    2700            PERGAMINO     BUENOS AIRES   
603           AR             BA    1686           HURLINGHAM     BUENOS AIRES   

       localidad_por_cp departamento_por_cp  
447  NO UNICA LOCALIDAD                None  
717  NO UNICA LOCALIDAD                None  
17        CP INDEFINIDO                None  
824  NO UNICA LOCALIDAD                None  
603          HURLINGHAM                None

## Breves analisis de la primera parte

In [88]:
augmented_df.shape

(1415, 7)

In [89]:
augmented_df.loc[augmented_df.provincia_por_cp == 'NO UNICA PROVINCIA'].shape

(22, 7)

In [90]:
augmented_df.loc[augmented_df.provincia_por_cp == 'CP INDEFINIDO'].shape

(185, 7)

In [91]:
augmented_df.loc[(augmented_df.provincia_por_cp != 'NO UNICA PROVINCIA') & (augmented_df.provincia_por_cp != 'CP INDEFINIDO')].shape

(1208, 7)

In [92]:
1208/1415*100

85.37102473498234

---

In [93]:
augmented_df.loc[augmented_df.localidad_por_cp == 'NO UNICA LOCALIDAD'].shape

(807, 7)

In [94]:
augmented_df.loc[(augmented_df.localidad_por_cp != 'NO UNICA LOCALIDAD') & (augmented_df.localidad_por_cp != 'CP INDEFINIDO')].shape

(423, 7)

In [95]:
augmented_df.loc[augmented_df.localidad_por_cp == 'CP INDEFINIDO'].shape

(185, 7)

In [96]:
423/1415 * 100

29.89399293286219

---

In [97]:
augmented_df.loc[(augmented_df.departamento_por_cp.notna()) & (augmented_df.departamento_por_cp != 'NO UNICO DEPARTAMENTO')] 

nacionalidad provincia_part cp_part           loc_part  \
41             AR            NaN    1217    CAPITAL FEDERAL   
415            AR             BA    1271  capilla del señor   
1249           AR             CH    1027               CABA   

                     provincia_por_cp localidad_por_cp departamento_por_cp  
41    CIUDAD AUTONOMA DE BUENOS AIRES        SAN TELMO            COMUNA 1  
415   CIUDAD AUTONOMA DE BUENOS AIRES         BARRACAS            COMUNA 4  
1249  CIUDAD AUTONOMA DE BUENOS AIRES        BALVANERA            COMUNA 3

Si bien el sistema funciona, se puede ver como claramente la persona se confundio el CP en el caso de `Capilla del Señor`

### CONCLUSIONES 

El CP es util para asignar localidades en un 29.89 % de los casos.<BR>
El CP es util para asignar provincias en un 85.37 % de los casos.

## Paso dos del algoritmo. Consultar la API

In [98]:
augmented_df['provincia_por_API'] = None
augmented_df['localidad_por_API'] = None
augmented_df['departamento_por_API'] = None
augmented_df['centroide_lat_localidad'] = None
augmented_df['centroide_lon_localidad'] = None
augmented_df['centroide_lat_departamento'] = None
augmented_df['centroide_lon_departamento'] = None
augmented_df['centroide_lat_provincia'] = None
augmented_df['centroide_lon_provincia'] = None
augmented_df.loc_part = augmented_df.loc_part.apply(lambda x: str(x).upper()) #Poner todo en mayuscula

Creare una lista aparte con provincia y localidad. Excluyendo las provincias y localidades no definidas. Es decir remover `NO UNICA LOCALIDAD`,`NO UNICA PROVINCIA` y `CP INDEFINIDO`

In [99]:
gby_prov_loc = augmented_df.groupby(['provincia_por_cp','localidad_por_cp']).count().reset_index(level=['provincia_por_cp', 'localidad_por_cp']).copy()
gby_prov_loc = gby_prov_loc.loc[(gby_prov_loc.localidad_por_cp != 'NO UNICA LOCALIDAD') & (gby_prov_loc.localidad_por_cp != 'CP INDEFINIDO')]
gby_prov_loc = gby_prov_loc.loc[(gby_prov_loc.provincia_por_cp != 'NO UNICA PROVINCIA') & (gby_prov_loc.provincia_por_cp != 'CP INDEFINIDO')]
gby_prov_loc.shape

(83, 16)

In [100]:
gby_prov_loc.sample(5)

provincia_por_cp localidad_por_cp  nacionalidad  provincia_part  cp_part  \
44     BUENOS AIRES     PASO DEL REY             4               3        4   
31     BUENOS AIRES        LA SALADA             5               3        5   
65     BUENOS AIRES    VICENTE LOPEZ             3               3        3   
77     BUENOS AIRES            WILDE             7               5        7   
19     BUENOS AIRES   GONZALEZ CATAN             7               5        7   

    loc_part  departamento_por_cp  provincia_por_API  localidad_por_API  \
44         4                    0                  0                  0   
31         5                    0                  0                  0   
65         3                    0                  0                  0   
77         7                    0                  0                  0   
19         7                    0                  0                  0   

    departamento_por_API  centroide_lat_localidad  centroide_lon_localidad  \
44                     0                        0                        0   
31                     0                        0                        0   
65                     0                        0                        0   
77                     0                        0                        0   
19                     0                        0                        0   

    centroide_lat_departamento  centroide_lon_departamento  \
44                           0                           0   
31                           0                           0   
65                           0                           0   
77                           0                           0   
19                           0                           0   

    centroide_lat_provincia  centroide_lon_provincia  
44                        0                        0  
31                        0                        0  
65                        0                        0  
77                        0                        0  
19                        0                        0

In [185]:
# crea una lista de tuplas para realizar el post
import get_centroides as geo
prov_loc = list(gby_prov_loc.apply(lambda x: (x.provincia_por_cp, x.localidad_por_cp), axis=1))

In [186]:
prov_loc[:5]

[('BUENOS AIRES', 'AEROPUERTO EZEIZA'),
 ('BUENOS AIRES', 'ALEJANDRO KORN'),
 ('BUENOS AIRES', 'BANFIELD'),
 ('BUENOS AIRES', 'BECCAR'),
 ('BUENOS AIRES', 'BELLA VISTA')]

In [187]:
#Realizo un POST request para pedir todos de una y no hacer multiples request (limite 5000).
datos = geo.post_centroides('localidades', prov_loc)

In [188]:
len(datos)

83

In [108]:
def get_field(i, field1, field2 = None):
        if len(i) == 0:
            return 'NO HUBO REQUEST'
        else: 
            if field2: 
                return i[field1][field2]       
            else: 
                return i[field1]


In [190]:
gby_prov_loc['provincia_por_API'] = [get_field(i,'provincia','nombre').upper() for i in datos]

In [191]:
gby_prov_loc['localidad_por_API'] = [get_field(i,'nombre').upper() for i in datos]
gby_prov_loc['centroide_lat_localidad'] = [get_field(i,'centroide','lat') for i in datos]
gby_prov_loc['centroide_lon_localidad'] = [get_field(i,'centroide','lon') for i in datos]

In [192]:
gby_prov_loc.sample(5)

provincia_por_cp localidad_por_cp  nacionalidad  provincia_part  cp_part  \
65     BUENOS AIRES    VICENTE LOPEZ             3               3        3   
33     BUENOS AIRES         LIBERTAD             5               3        5   
45     BUENOS AIRES          QUILMES             6               5        6   
60     BUENOS AIRES          SARANDI             8               5        8   
18     BUENOS AIRES             GLEW             3               2        3   

    loc_part  departamento_por_cp provincia_por_API localidad_por_API  \
65         3                    0      BUENOS AIRES     VICENTE LOPEZ   
33         5                    0      BUENOS AIRES          LIBERTAD   
45         6                    0      BUENOS AIRES           QUILMES   
60         8                    0      BUENOS AIRES           SARANDI   
18         3                    0      BUENOS AIRES              GLEW   

    departamento_por_API centroide_lat_localidad centroide_lon_localidad  \
65                     0                -34.5255                -58.4736   
33                     0                -34.7085                -58.6796   
45                     0                -34.7241                -58.2492   
60                     0                -34.6844                -58.3481   
18                     0                 -34.886                -58.3818   

    centroide_lat_departamento  centroide_lon_departamento  
65                           0                           0  
33                           0                           0  
45                           0                           0  
60                           0                           0  
18                           0                           0

In [105]:
gby_prov_loc[gby_prov_loc.provincia_por_API == 'NO HUBO REQUEST'] 

provincia_por_cp       localidad_por_cp  nacionalidad  provincia_part  \
11     BUENOS AIRES          CIUDAD MADERO            14              12   
27     BUENOS AIRES      JOSE CLEMENTE PAZ            10               6   
43     BUENOS AIRES               NORDELTA             3               3   
54     BUENOS AIRES  SAN BERNARDO DEL TUYU             5               5   

    cp_part  loc_part  departamento_por_cp provincia_por_API  \
11       14        14                    0   NO HUBO REQUEST   
27       10        10                    0   NO HUBO REQUEST   
43        3         3                    0   NO HUBO REQUEST   
54        5         5                    0   NO HUBO REQUEST   

   localidad_por_API centroide_lat_localidad centroide_lon_localidad  
11   NO HUBO REQUEST         NO HUBO REQUEST         NO HUBO REQUEST  
27   NO HUBO REQUEST         NO HUBO REQUEST         NO HUBO REQUEST  
43   NO HUBO REQUEST         NO HUBO REQUEST         NO HUBO REQUEST  
54   NO HUBO REQUEST         NO HUBO REQUEST         NO HUBO REQUEST

4 Localidades bien definidas no encontraron request. Indagar por que no estan en la API

In [113]:
geo.get_centroides('municipios', 'jose paz', provincia = 'buenos aires', max = 2)

[{'centroide': {'lat': -38.5808546732895, 'lon': -62.1656895327094},
  'id': '060056',
  'nombre': 'Bahía Blanca',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {'centroide': {'lat': -38.2027130466249, 'lon': -58.0722485722111},
  'id': '060280',
  'nombre': 'General Alvarado',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}}]

In [114]:
geo.get_centroides('municipios', 'jose c. paz', provincia = 'buenos aires', max = 2) #La api esta andando mal para el GET
# Cheque esto con la base entera de localidades y no tiene sentido el output

[{'centroide': {'lat': -38.5808546732895, 'lon': -62.1656895327094},
  'id': '060056',
  'nombre': 'Bahía Blanca',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {'centroide': {'lat': -38.2027130466249, 'lon': -58.0722485722111},
  'id': '060280',
  'nombre': 'General Alvarado',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}}]

### 2.2 Chequear solo comunas

In [193]:
gby_comunas = augmented_df.loc[(augmented_df.provincia_por_cp == 'CIUDAD AUTONOMA DE BUENOS AIRES')  &
                               (augmented_df.localidad_por_cp == 'NO UNICA LOCALIDAD') &
                               (augmented_df.localidad_por_cp == 'NO UNICA LOCALIDAD')].copy()

In [194]:
gby_comunas

nacionalidad provincia_part cp_part          loc_part  \
34             AR            NaN    1414              CABA   
35             AR            NaN    1425              CABA   
306            AR             BA    1406     12 DE OCTUBRE   
308            AR             BA    1427       16 DE JULIO   
330            AR             BA    1425             AGOTE   
402            AR             BA    1424              CABA   
403            AR             BA    1407              CABA   
407            AR             BA    1428  CAMPO LOS AROMOS   
555            AR             BA    1425  GENERAL BELGRANO   
698            AR             BA    1408           LINIERS   
961            UY             BA    1425          TAPIARES   
991            AR             BA    1431           URQUIZA   
1112           AR             CB    1181              CABA   
1132           AR             CF    1425                -1   
1140           AR             CF    1416              CABA   
1141           AR             CF    1416              CABA   
1142           AR             CF    1007       CABA RETIRO   
1145           AR             CF    1431           CAPITAL   
1163           AR             CF    1425          CUERPO 2   
1165           AR             CF    1431           DTO 308   
1166           AR             CF    1431           DTO 308   
1214           AR             CF    1437           POMPEYA   
1215           AR             CF    1437           POMPEYA   
1241           AR             CF    1417  VILLA DEL PARQUE   
1276           AR             ER    1158              CABA   
1342           AR             RN    1425              CABA   
1375           AR             SF    1427              CABA   
1376           AR             SF    1181              CABA   

                     provincia_por_cp    localidad_por_cp  \
34    CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
35    CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
306   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
308   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
330   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
402   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
403   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
407   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
555   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
698   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
961   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
991   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1112  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1132  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1140  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1141  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1142  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1145  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1163  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1165  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1166  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1214  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1215  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1241  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1276  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1342  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1375  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1376  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   

        departamento_por_cp provincia_por_API localidad_por_API  \
34    NO UNICO DEPARTAMENTO              None              None   
35    NO UNICO DEPARTAMENTO              None              None   
306   NO UNICO DEPARTAMENTO              None              None   
308   NO UNICO DEPARTAMENTO              None              None   
330   NO UNICO DEPARTAMENTO              None              None   
402   NO UNICO DEPARTAMENTO       

En nuestro caso no hay casos de COMUNA identificada sin identificar localidad

In [144]:
gby_comunas = augmented_df.loc[(augmented_df.provincia_por_cp == 'CIUDAD AUTONOMA DE BUENOS AIRES')  &
                               (augmented_df.localidad_por_cp == 'NO UNICA LOCALIDAD') &
                               (augmented_df.departamento_por_cp == 'NO UNICA DEPARTAMENTO')].copy()

In [145]:
gby_comunas

Empty DataFrame
Columns: [nacionalidad, provincia_part, cp_part, loc_part, provincia_por_cp, localidad_por_cp, departamento_por_cp]
Index: []

In [147]:
gby_comunas['centroide_lat_departamento'] = None
gby_comunas['centroide_lon_departamento'] = None

In [161]:
comunas = list(gby_comunas.apply(lambda x: (x.provincia_por_cp, x.departamento_por_cp), axis=1))
comunas

[(nan, nan)]

In [151]:
#comunas = [('CIUDAD AUTONOMA DE BUENOS AIRES','COMUNA 14')]   ejemplo para ver que devolveria
comunas

[('CIUDAD AUTONOMA DE BUENOS AIRES', 'COMUNA 14')]

In [155]:
datos = geo.post_centroides('departamentos', comunas)
datos

[{'centroide': {'lat': -34.5738372943158, 'lon': -58.4222211632133},
  'id': '02098',
  'nombre': 'Comuna 14',
  'provincia': {'id': '02', 'nombre': 'Ciudad Autónoma de Buenos Aires'}}]

In [160]:
gby_comunas['centroide_lat_departamento'] = [get_field(i,'centroide','lat') for i in datos]
gby_comunas['centroide_lon_departamento'] = [get_field(i,'centroide','lon') for i in datos]

nacionalidad provincia_part cp_part loc_part provincia_por_cp  \
0          NaN            NaN     NaN      NaN              NaN   

  localidad_por_cp departamento_por_cp centroide_lat_comuna  \
0              NaN                 NaN                  NaN   

  centroide_lon_comuna  centroide_lat_localidad  centroide_lon_localidad  
0                  NaN               -34.573837               -58.422221

---

## Chequear LOC PART con datos de provincia
2.1.2) Si no hay localidad habra dos opciones, dependiendo si es de Capital o Provincia:
Provincia) Se usa la provincia como campo y se usa el campo loc_part (ingresado por el usuario). Si encuentra se agrega la localidad. Sino se agrega centroide de la provincia.

Capital) Se usa la comuna si la hay y se busca por departamento. Sino se usa el campo 'loc_part' como localidad. Es probabable que no devuelva dato por lo que solo se agrega centroide de Capital Federal. Si devuelve datos se agrega la comuna y no la localidad.

In [202]:
augmented_df.loc[augmented_df.localidad_por_cp == 'NO UNICA LOCALIDAD']

nacionalidad provincia_part cp_part             loc_part  \
3              AR            NaN    6660           25 DE MAYO   
6              AR            NaN    1770           ALDO BONZI   
7              AR            NaN    1770           ALDO BONZI   
11             AR            NaN    1870           AVELLANEDA   
20             AR            NaN    1884          BERAZATEGUI   
...           ...            ...     ...                  ...   
1410           AR             TU    4000  SAN MIGUEL DE TUCUM   
1411           AR             TU    4000  SAN MIGUEL DE TUCUM   
1412           AR             TU    4107              TUCUMAN   
1413           AR             TU    4107          YERBA BUENA   
1414           AR             TU    4107          YERBA BUENA   

     provincia_por_cp    localidad_por_cp departamento_por_cp  \
3        BUENOS AIRES  NO UNICA LOCALIDAD                None   
6        BUENOS AIRES  NO UNICA LOCALIDAD                None   
7        BUENOS AIRES  NO UNICA LOCALIDAD                None   
11       BUENOS AIRES  NO UNICA LOCALIDAD                None   
20       BUENOS AIRES  NO UNICA LOCALIDAD                None   
...               ...                 ...                 ...   
1410          TUCUMÁN  NO UNICA LOCALIDAD                None   
1411          TUCUMÁN  NO UNICA LOCALIDAD                None   
1412          TUCUMÁN  NO UNICA LOCALIDAD                None   
1413          TUCUMÁN  NO UNICA LOCALIDAD                None   
1414          TUCUMÁN  NO UNICA LOCALIDAD                None   

     provincia_por_API localidad_por_API departamento_por_API  \
3                 None              None                 None   
6                 None              None                 None   
7                 None              None                 None   
11                None              None                 None   
20                None              None                 None   
...                ...               ...                  ...   
1410              None              None                 None   
1411              None              None                 None   
1412              None              None                 None   
1413              None              None                 None   
1414              None              None                 None   

     centroide_lat_localidad centroide_lon_localidad  \
3                       None                    None   
6                       None                    None   
7                       None                    None   
11                      None                    None   
20                      None                    None   
...                      ...                     ...   
1410                    None                    None   
1411                    None                    None   
1412                    None                    None   
1413                    None                    None   
1414                    None                    None   

     centroide_lat_departamento centroide_lon_departamento  
3                          None                       None  
6                          None                       None  
7                          None                       None  
11                         None                       None  
20                         None                       None  
...                         ...                        ...  
1410                       None                       None  
1411                       None                       None  
1412                       None                       None  
1413                       None                       None  
1414                       None                       None  

[807 rows x 14 columns]

In [207]:
gby_solo_provincia = augmented_df.groupby(['loc_part', 'provincia_por_cp']).count().reset_index(['loc_part','provincia_por_cp']) # con este subset armar un post request
gby_solo_provincia = gby_solo_provincia.loc[(gby_solo_provincia.provincia_por_cp != 'CP INDEFINIDO') & (gby_solo_provincia.provincia_por_cp != 'NO UNICA PROVINCIA')]
print(gby_solo_provincia.shape)
gby_solo_provincia.sample(10)

(616, 14)


loc_part provincia_por_cp  nacionalidad  provincia_part  \
133              CHARATA            CHACO             2               2   
138         CHOELE CHOEL        RÍO NEGRO             1               1   
595           SAN JULIAN     BUENOS AIRES             2               2   
710  VILLA GENERAL BELGR          CÓRDOBA             1               1   
463             NORDELTA     BUENOS AIRES             1               1   
342           LA MATILDE     BUENOS AIRES             1               1   
613          SAN VICENTE     BUENOS AIRES             2               2   
244    GENERAL LAS HERAS     BUENOS AIRES             2               2   
257    GERLI.-AVELLANEDA     BUENOS AIRES             1               1   
667            V ADELINA     BUENOS AIRES             1               0   

     cp_part  localidad_por_cp  departamento_por_cp  provincia_por_API  \
133        2                 2                    0                  0   
138        1                 1                    0                  0   
595        2                 2                    0                  0   
710        1                 1                    0                  0   
463        1                 1                    0                  0   
342        1                 1                    0                  0   
613        2                 2                    0                  0   
244        2                 2                    0                  0   
257        1                 1                    0                  0   
667        1                 1                    0                  0   

     localidad_por_API  departamento_por_API  centroide_lat_localidad  \
133                  0                     0                        0   
138                  0                     0                        0   
595                  0                     0                        0   
710                  0                     0                        0   
463                  0                     0                        0   
342                  0                     0                        0   
613                  0                     0                        0   
244                  0                     0                        0   
257                  0                     0                        0   
667                  0                     0                        0   

     centroide_lon_localidad  centroide_lat_departamento  \
133                        0                           0   
138                        0                           0   
595                        0                           0   
710                        0                           0   
463                        0                           0   
342                        0                           0   
613                        0                           0   
244                        0                           0   
257                        0                           0   
667                        0                           0   

     centroide_lon_departamento  
133                           0  
138                           0  
595                           0  
710                           0  
463                           0  
342                           0  
613                           0  
244                           0  
257                           0  
667                           0

In [211]:
prov_loc_part = list(gby_solo_provincia.apply(lambda x: (x.provincia_por_cp, x.loc_part), axis=1))
len(prov_loc_part)

616

In [209]:
prov_loc_part[:7]

[('BUENOS AIRES', ' VENEZUELA Y PERU'),
 ('BUENOS AIRES', '-1'),
 ('CIUDAD AUTONOMA DE BUENOS AIRES', '-1'),
 ('SAN JUAN', '-1'),
 ('SAN LUIS', '-1'),
 ('BUENOS AIRES', '10064'),
 ('BUENOS AIRES', '12 DE AGOSTO')]

In [212]:
datos = geo.post_centroides('localidades', prov_loc_part)

In [214]:
datos[5:12]

[{},
 {},
 {'categoria': 'Localidad simple',
  'centroide': {'lat': -35.607730780146, 'lon': -60.9182929927645},
  'departamento': {'id': '06588', 'nombre': '9 de Julio'},
  'id': '06588030000',
  'localidad_censal': {'id': '06588030', 'nombre': '12 de Octubre'},
  'municipio': {'id': '060588', 'nombre': '9 de Julio'},
  'nombre': '12 DE OCTUBRE',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {},
 {'categoria': 'Localidad simple',
  'centroide': {'lat': -37.2020524773603, 'lon': -60.1652139181813},
  'departamento': {'id': '06049', 'nombre': 'Azul'},
  'id': '06049050000',
  'localidad_censal': {'id': '06049050', 'nombre': '16 de Julio'},
  'municipio': {'id': '060049', 'nombre': 'Azul'},
  'nombre': '16 DE JULIO',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {},
 {'categoria': 'Localidad simple',
  'centroide': {'lat': -37.9086924428976, 'lon': -62.9360284730803},
  'departamento': {'id': '06651', 'nombre': 'Puán'},
  'id': '06651040000',
  'localidad_censal': {

In [215]:
gby_solo_provincia['provincia_por_API'] = [get_field(i,'provincia','nombre').upper() for i in datos]
gby_solo_provincia['localidad_por_API'] = [get_field(i,'nombre').upper() for i in datos]
gby_solo_provincia['centroide_lat_localidad'] = [get_field(i,'centroide','lat') for i in datos]
gby_solo_provincia['centroide_lon_localidad'] = [get_field(i,'centroide','lon') for i in datos]

In [217]:
gby_solo_provincia.sample(7)

loc_part     provincia_por_cp  nacionalidad  provincia_part  \
682           VICTORIA         BUENOS AIRES             2               2   
442      MONTE CASEROS           CORRIENTES             2               2   
755              WILDE         BUENOS AIRES             6               4   
228  FLORIDA-VTE LOPEZ         BUENOS AIRES             1               1   
245  GENERAL MADARIAGA         BUENOS AIRES             2               2   
16        30 DE AGOSTO         BUENOS AIRES             1               1   
328           LA BANDA  SANTIAGO DEL ESTERO             1               1   

     cp_part  localidad_por_cp  departamento_por_cp  provincia_por_API  \
682        2                 2                    0                  0   
442        2                 2                    0                  0   
755        6                 6                    0                  0   
228        1                 1                    0                  0   
245        2                 2                    0                  0   
16         1                 1                    0                  0   
328        1                 1                    0                  0   

          localidad_por_API  departamento_por_API centroide_lat_localidad  \
682                VICTORIA                     0                 -34.462   
442           MONTE CASEROS                     0                -30.2516   
755                   WILDE                     0                -34.7062   
228         NO HUBO REQUEST                     0         NO HUBO REQUEST   
245  GENERAL JUAN MADARIAGA                     0                -36.9968   
16             30 DE AGOSTO                     0                 -36.278   
328                LA BANDA                     0                -27.7339   

    centroide_lon_localidad  centroide_lat_departamento  \
682                -58.5596                           0   
442                -57.6388                           0   
755                -58.3218                           0   
228         NO HUBO REQUEST                           0   
245                -57.1375                           0   
16                 -62.5453                           0   
328                 -64.239                           0   

     centroide_lon_departamento  
682                           0  
442                           0  
755                           0  
228                           0  
245                           0  
16                            0  
328                           0

### Ahora con los CP INDEFINIDO y NO UNICA PROVINCIA 

In [101]:
gby_sin_datos = augmented_df.groupby(['loc_part', 'provincia_por_cp']).count().reset_index(['loc_part','provincia_por_cp']) # con este subset armar un post request
gby_sin_datos = gby_sin_datos.loc[(gby_sin_datos.provincia_por_cp == 'CP INDEFINIDO') | (gby_sin_datos.provincia_por_cp == 'NO UNICA PROVINCIA')]
print(gby_sin_datos.shape)
gby_sin_datos

(144, 16)


loc_part    provincia_por_cp  nacionalidad  provincia_part  \
7       12 DE AGOSTO       CP INDEFINIDO             1               1   
18        9 DE ABRIL       CP INDEFINIDO             2               0   
21            ABASTO       CP INDEFINIDO             1               1   
22          ACASSUSO       CP INDEFINIDO             2               2   
35            ALICIA       CP INDEFINIDO             1               1   
..               ...                 ...           ...             ...   
737     VILLA REGINA  NO UNICA PROVINCIA             1               1   
743  VILLA SARMIENTO       CP INDEFINIDO             2               2   
744    VILLA SOLDATI       CP INDEFINIDO             2               2   
749          VILLARS       CP INDEFINIDO             2               2   
752  VIRREY DEL PINO       CP INDEFINIDO             2               0   

     cp_part  localidad_por_cp  departamento_por_cp  provincia_por_API  \
7          1                 1                    0                  0   
18         2                 2                    0                  0   
21         1                 1                    0                  0   
22         2                 2                    0                  0   
35         1                 1                    0                  0   
..       ...               ...                  ...                ...   
737        1                 1                    0                  0   
743        2                 2                    0                  0   
744        2                 2                    0                  0   
749        2                 2                    0                  0   
752        2                 2                    0                  0   

     localidad_por_API  departamento_por_API  centroide_lat_localidad  \
7                    0                     0                        0   
18                   0                     0                        0   
21                   0                     0                        0   
22                   0                     0                        0   
35                   0                     0                        0   
..                 ...                   ...                      ...   
737                  0                     0                        0   
743                  0                     0                        0   
744                  0                     0                        0   
749                  0                     0                        0   
752                  0                     0                        0   

     centroide_lon_localidad  centroide_lat_departamento  \
7                          0                           0   
18                         0                           0   
21                         0                           0   
22                         0                           0   
35                         0                           0   
..                       ...                         ...   
737                        0                           0   
743                        0                           0   
744                        0                           0   
749                        0                           0   
752                        0                           0   

     centroide_lon_departamento  centroide_lat_provincia  \
7                             0                        0   
18                            0                        0   
21                            0                        0   
22                            0                        0   
35                            0                        0   
..                          ...                      ...   
737                           0                        0   
743                           0                        0   
744                           0                        0   
749                           0     

In [102]:
solo_loc = gby_sin_datos.loc_part
datos = geo.post_centroides('localidades', solo_loc, prov = False)

In [106]:
datos[:3]

[{},
 {'categoria': 'Entidad',
  'centroide': {'lat': -34.7565075768115, 'lon': -58.4902923509723},
  'departamento': {'id': '06260', 'nombre': 'Esteban Echeverría'},
  'id': '06260010005',
  'localidad_censal': {'id': '06260010', 'nombre': 'Esteban Echeverría'},
  'municipio': {'id': '060260', 'nombre': 'Esteban Echeverría'},
  'nombre': '9 DE ABRIL',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}},
 {'categoria': 'Entidad',
  'centroide': {'lat': -35.0103681960184, 'lon': -58.1151848585184},
  'departamento': {'id': '06441', 'nombre': 'La Plata'},
  'id': '06441030001',
  'localidad_censal': {'id': '06441030', 'nombre': 'La Plata'},
  'municipio': {'id': '060441', 'nombre': 'La Plata'},
  'nombre': 'ABASTO',
  'provincia': {'id': '06', 'nombre': 'Buenos Aires'}}]

In [109]:
gby_sin_datos['provincia_por_API'] = [get_field(i,'provincia','nombre').upper() for i in datos]
gby_sin_datos['localidad_por_API'] = [get_field(i,'nombre').upper() for i in datos]
gby_sin_datos['centroide_lat_localidad'] = [get_field(i,'centroide','lat') for i in datos]
gby_sin_datos['centroide_lon_localidad'] = [get_field(i,'centroide','lon') for i in datos]

In [110]:
gby_sin_datos

loc_part    provincia_por_cp  nacionalidad  provincia_part  \
7       12 DE AGOSTO       CP INDEFINIDO             1               1   
18        9 DE ABRIL       CP INDEFINIDO             2               0   
21            ABASTO       CP INDEFINIDO             1               1   
22          ACASSUSO       CP INDEFINIDO             2               2   
35            ALICIA       CP INDEFINIDO             1               1   
..               ...                 ...           ...             ...   
737     VILLA REGINA  NO UNICA PROVINCIA             1               1   
743  VILLA SARMIENTO       CP INDEFINIDO             2               2   
744    VILLA SOLDATI       CP INDEFINIDO             2               2   
749          VILLARS       CP INDEFINIDO             2               2   
752  VIRREY DEL PINO       CP INDEFINIDO             2               0   

     cp_part  localidad_por_cp  departamento_por_cp  \
7          1                 1                    0   
18         2                 2                    0   
21         1                 1                    0   
22         2                 2                    0   
35         1                 1                    0   
..       ...               ...                  ...   
737        1                 1                    0   
743        2                 2                    0   
744        2                 2                    0   
749        2                 2                    0   
752        2                 2                    0   

                   provincia_por_API localidad_por_API  departamento_por_API  \
7                    NO HUBO REQUEST   NO HUBO REQUEST                     0   
18                      BUENOS AIRES        9 DE ABRIL                     0   
21                      BUENOS AIRES            ABASTO                     0   
22                      BUENOS AIRES          ACASSUSO                     0   
35                           CÓRDOBA            ALICIA                     0   
..                               ...               ...                   ...   
737                        RÍO NEGRO      VILLA REGINA                     0   
743                     BUENOS AIRES   VILLA SARMIENTO                     0   
744  CIUDAD AUTÓNOMA DE BUENOS AIRES     VILLA SOLDATI                     0   
749                     BUENOS AIRES           VILLARS                     0   
752                     BUENOS AIRES   VIRREY DEL PINO                     0   

    centroide_lat_localidad centroide_lon_localidad  \
7           NO HUBO REQUEST         NO HUBO REQUEST   
18                 -34.7565                -58.4903   
21                 -35.0104                -58.1152   
22                 -34.4794                -58.5074   
35                 -31.9387                -62.4658   
..                      ...                     ...   
737                -39.0963                -67.0828   
743                -34.6347                -58.5716   
744                -34.6655                -58.4465   
749                  -34.83                -58.9423   
752                -34.8475                -58.6861   

     centroide_lat_departamento  centroide_lon_departamento  \
7                             0                           0   
18                            0                           0   
21                            0                           0   
22                            0                           0   
35                            0                           0   
..                          ...                         ...   
737                           0                           0   
743                           0                           0   
744                           0                           0   
749                           0                           0   
752                           0                           0   

     centroide_lat_provincia  centroide_lon_provincia  
7                          

In [112]:
gby_sin_datos.loc[gby_sin_datos.localidad_por_API == 'NO HUBO REQUEST'].shape

(27, 16)

In [113]:
27/114

0.23684210526315788

Un 23% de request no arrojaron resultados. Sin embargo esto es solamente el 23% del +- 10% del dataset total

###  Capital sin localidad definida

In [118]:
gby_cap_sin_loc = augmented_df.loc[(augmented_df.provincia_por_cp == 'CIUDAD AUTONOMA DE BUENOS AIRES')]
gby_cap_sin_loc = gby_cap_sin_loc.loc[(gby_cap_sin_loc.localidad_por_cp == 'NO UNICA LOCALIDAD')]
print(gby_cap_sin_loc.shape)
gby_cap_sin_loc.sample(5)

(28, 16)


nacionalidad provincia_part cp_part          loc_part  \
991            AR             BA    1431           URQUIZA   
1376           AR             SF    1181              CABA   
1166           AR             CF    1431           DTO 308   
407            AR             BA    1428  CAMPO LOS AROMOS   
403            AR             BA    1407              CABA   

                     provincia_por_cp    localidad_por_cp  \
991   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1376  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1166  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
407   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
403   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   

        departamento_por_cp provincia_por_API localidad_por_API  \
991   NO UNICO DEPARTAMENTO              None              None   
1376  NO UNICO DEPARTAMENTO              None              None   
1166  NO UNICO DEPARTAMENTO              None              None   
407   NO UNICO DEPARTAMENTO              None              None   
403   NO UNICO DEPARTAMENTO              None              None   

     departamento_por_API centroide_lat_localidad centroide_lon_localidad  \
991                  None                    None                    None   
1376                 None                    None                    None   
1166                 None                    None                    None   
407                  None                    None                    None   
403                  None                    None                    None   

     centroide_lat_departamento centroide_lon_departamento  \
991                        None                       None   
1376                       None                       None   
1166                       None                       None   
407                        None                       None   
403                        None                       None   

     centroide_lat_provincia centroide_lon_provincia  
991                     None                    None  
1376                    None                    None  
1166                    None                    None  
407                     None                    None  
403                     None                    None

In [119]:
cap_sin_loc = list(gby_cap_sin_loc.apply(lambda x: (x.provincia_por_cp, x.loc_part), axis=1))

In [125]:
cap_sin_loc[:5]

[('CIUDAD AUTONOMA DE BUENOS AIRES', 'CABA'),
 ('CIUDAD AUTONOMA DE BUENOS AIRES', 'CABA'),
 ('CIUDAD AUTONOMA DE BUENOS AIRES', '12 DE OCTUBRE'),
 ('CIUDAD AUTONOMA DE BUENOS AIRES', '16 DE JULIO'),
 ('CIUDAD AUTONOMA DE BUENOS AIRES', 'AGOTE')]

In [126]:
datos = geo.post_centroides('localidades', cap_sin_loc)

In [127]:
gby_cap_sin_loc['provincia_por_API'] = [get_field(i,'provincia','nombre').upper() for i in datos]
gby_cap_sin_loc['departamento_por_API'] = [get_field(i,'departamento','nombre').upper() for i in datos]
gby_cap_sin_loc['localidad_por_API'] = [get_field(i,'nombre').upper() for i in datos]
gby_cap_sin_loc['centroide_lat_localidad'] = [get_field(i,'centroide','lat') for i in datos]
gby_cap_sin_loc['centroide_lon_localidad'] = [get_field(i,'centroide','lon') for i in datos]

In [128]:
gby_cap_sin_loc

nacionalidad provincia_part cp_part          loc_part  \
34             AR            NaN    1414              CABA   
35             AR            NaN    1425              CABA   
306            AR             BA    1406     12 DE OCTUBRE   
308            AR             BA    1427       16 DE JULIO   
330            AR             BA    1425             AGOTE   
402            AR             BA    1424              CABA   
403            AR             BA    1407              CABA   
407            AR             BA    1428  CAMPO LOS AROMOS   
555            AR             BA    1425  GENERAL BELGRANO   
698            AR             BA    1408           LINIERS   
961            UY             BA    1425          TAPIARES   
991            AR             BA    1431           URQUIZA   
1112           AR             CB    1181              CABA   
1132           AR             CF    1425                -1   
1140           AR             CF    1416              CABA   
1141           AR             CF    1416              CABA   
1142           AR             CF    1007       CABA RETIRO   
1145           AR             CF    1431           CAPITAL   
1163           AR             CF    1425          CUERPO 2   
1165           AR             CF    1431           DTO 308   
1166           AR             CF    1431           DTO 308   
1214           AR             CF    1437           POMPEYA   
1215           AR             CF    1437           POMPEYA   
1241           AR             CF    1417  VILLA DEL PARQUE   
1276           AR             ER    1158              CABA   
1342           AR             RN    1425              CABA   
1375           AR             SF    1427              CABA   
1376           AR             SF    1181              CABA   

                     provincia_por_cp    localidad_por_cp  \
34    CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
35    CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
306   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
308   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
330   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
402   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
403   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
407   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
555   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
698   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
961   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
991   CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1112  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1132  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1140  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1141  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1142  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1145  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1163  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1165  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1166  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1214  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1215  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1241  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1276  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1342  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1375  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   
1376  CIUDAD AUTONOMA DE BUENOS AIRES  NO UNICA LOCALIDAD   

        departamento_por_cp                provincia_por_API  \
34    NO UNICO DEPARTAMENTO  CIUDAD AUTÓNOMA DE BUENOS AIRES   
35    NO UNICO DEPARTAMENTO  CIUDAD AUTÓNOMA DE BUENOS AIRES   
306   NO UNICO DEPARTAMENTO                  NO HUBO REQUEST   
308   NO UNICO DEPARTAMENTO                  NO HUBO REQUEST   
330   NO UNICO DEPARTAMENTO                  NO HUBO REQUEST   
402   NO UNICO DEPARTAMENTO  CIUDAD AUTÓNOMA DE BUEN


La API tiende a asignar CABALLITO y Comuna 6 como localidad y departamento por defecto. Debido a que se encuentran en el medio de la capital.